version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: reits_mysql
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: reits_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker_data/mysql:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:7.17.10
    container_name: reits_es
    network_mode: "host"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - ./docker_data/es:/usr/share/elasticsearch/data

  etcd:
    container_name: reits_etcd
    image: quay.io/coreos/etcd:v3.5.5
    network_mode: "host"
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./docker_data/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: reits_minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    network_mode: "host"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./docker_data/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"

  milvus:
    container_name: reits_milvus
    image: milvusdb/milvus:v2.2.11
    network_mode: "host"
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: 127.0.0.1:2379
      MINIO_ADDRESS: 127.0.0.1:9000
    volumes:
      - ./docker_data/milvus:/var/lib/milvus

  # ================= 新增 MinerU CPU 服务 =================
  # mineru:
  #   image: localhost/mineru-cpu:latest
  #   container_name: reits_mineru
  #   network_mode: "host"
  #   restart: unless-stopped
  #   environment:
  #     - MINERU_DEVICE_MODE=cpu
  #     - CUDA_VISIBLE_DEVICES=""
  #     - MINERU_MODEL_SOURCE=local
  #   # 【关键】挂载刚才成功下载的模型目录，宿主机相对路径 -> 容器内的 /root/.mineru
  #   volumes:
  #     - ./docker_data/mineru4_models:/root/.mineru
  #   # 启动命令，不要加 --backend 和 --device
  #   command: mineru-api --host 0.0.0.0 --port 8000
  #   # 【警告】千万不要在这里写 cpus 和 mem_limit，podman-compose 会报错！